### ISSUE TITLE
Cannot convert from SEK

### ISSUE THREAD

**Issue by ghost** [andreymatveev/jquery-inline-currency#1]
As the title says.
`<span class="jic" data-jic-currency="USD" data-jic-convert-to="EUR">100</span>`
works fine, converting the value "100" to EUR in a popup, but
`<span class="jic" data-jic-currency="SEK" data-jic-convert-to="EUR">100</span>`
(attempting to have a value in SEK that converts to EUR in a popup) does nothing. No popup shows.

The plugin is initialised with:
`$('.jic').inlineCurrency();`
and jquery.min.js, jquery.inline-currency.js and jquery.inline-currency.css is loaded in this order.

**Comment by andreymatveev** [comment]
@chatzopoulos Sorry for my very late answer. Somehow I've overlooked your issue and was really surprised this morning. This plugin had many bugs because I have abandoned it. But today I've made several changes, so, if you are still interested, you may try again.
